name: build

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  android:
    runs-on: ubuntu-latest

    env:
      PLATFORM: Android

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build with Gradle
        run: ./gradlew build

  web:
    runs-on: ubuntu-latest

    env:
      EMSCRIPTEN_VERSION: 3.1.46
      EMSCRIPTEN_CACHE_FOLDER: emsdk-cache

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Emscripten SDK Cache
        id: cache-system-libraries
        uses: actions/cache@v2
        with:
          path: ${{env.EMSCRIPTEN_CACHE_FOLDER}}
          key: ${{env.EMSCRIPTEN_VERSION}}-${{ runner.os }}

      - name: Setup Emscripten SDK
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{env.EMSCRIPTEN_VERSION}}
          actions-cache-folder: ${{env.EMSCRIPTEN_CACHE_FOLDER}}

      - name: Configure CMake
        run: >
          cmake
          -B "${{github.workspace}}/cmake-build-web"
          -D CMAKE_BUILD_TYPE="${{env.BUILD_TYPE}}"
          -D PLATFORM="Web"
          -D CMAKE_TOOLCHAIN_FILE="${{github.workspace}}/${{env.EMSCRIPTEN_CACHE_FOLDER}}/emsdk-main/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake"
          -D CMAKE_EXE_LINKER_FLAGS="-s USE_GLFW=3"
          -D CMAKE_EXECUTABLE_SUFFIX=".html"

      - name: Build
        run: cmake --build ${{github.workspace}}/cmake-build-web

  desktop-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/cmake-build-desktop-windows -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/cmake-build-desktop-windows

  desktop-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install raylib dependencies
        run: sudo apt update -y; sudo apt install -y libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/cmake-build-desktop-linux -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/cmake-build-desktop-linux
